"""add_watchlist_entries_table

Revision ID: e61438baa56b
Revises: 27a0e45223fc
Create Date: 2025-09-18 14:55:56.088089+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61438baa56b'
down_revision: Union[str, None] = '27a0e45223fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('added_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_active', 'watchlist_entries', ['is_active'], unique=False)
    op.create_index('idx_watchlist_stock_active', 'watchlist_entries', ['stock_id', 'is_active'], unique=False)
    op.alter_column('news_articles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reddit_posts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'stock_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_sentiment_data_content_hash'), 'sentiment_data', ['content_hash'], unique=False)
    op.alter_column('stock_prices', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('stock_prices', 'stock_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('stocks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('system_logs', sa.Column('logger', sa.String(length=100), nullable=False))
    op.add_column('system_logs', sa.Column('function', sa.String(length=100), nullable=True))
    op.add_column('system_logs', sa.Column('line_number', sa.Integer(), nullable=True))
    op.alter_column('system_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('system_logs', 'line_number')
    op.drop_column('system_logs', 'function')
    op.drop_column('system_logs', 'logger')
    op.alter_column('stocks', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('stock_prices', 'stock_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('stock_prices', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sentiment_data_content_hash'), table_name='sentiment_data')
    op.alter_column('sentiment_data', 'content_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sentiment_data', 'stock_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reddit_posts', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('news_articles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index('idx_watchlist_stock_active', table_name='watchlist_entries')
    op.drop_index('idx_watchlist_active', table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    # ### end Alembic commands ###
