"""Replace RedditPost with HackerNewsPost

Revision ID: 5940f66efa7e
Revises: d5414ad4710a
Create Date: 2025-11-28 08:41:34.672919+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5940f66efa7e'
down_revision: Union[str, None] = 'd5414ad4710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackernews_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=True),
    sa.Column('hn_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('story_id', sa.String(length=50), nullable=True),
    sa.Column('story_title', sa.String(length=500), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('stock_mentions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_watchlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hn_id')
    )
    op.drop_table('_alembic_tmp_sentiment_data')
    op.drop_table('reddit_posts')
    op.alter_column('news_articles', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('news_articles', 'stock_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('news_articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('news_articles', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('news_articles', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('news_articles', 'author',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('sentiment_data', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('sentiment_data', 'stock_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('sentiment_data', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'sentiment_score',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=4),
               nullable=False)
    op.alter_column('sentiment_data', 'sentiment_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Neutral'"))
    op.alter_column('sentiment_data', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sentiment_data', 'content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('idx_sentiment_duplicate_check', table_name='sentiment_data')
    op.create_index('idx_sentiment_duplicate_check', 'sentiment_data', ['stock_id', 'source', 'content_hash'], unique=False)
    op.create_index(op.f('ix_sentiment_data_content_hash'), 'sentiment_data', ['content_hash'], unique=False)
    op.create_index(op.f('ix_sentiment_data_sentiment_label'), 'sentiment_data', ['sentiment_label'], unique=False)
    op.create_foreign_key(None, 'sentiment_data', 'stocks_watchlist', ['stock_id'], ['id'])
    op.alter_column('stock_prices', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('stock_prices', 'stock_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('stock_prices', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('stock_prices', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.alter_column('stocks_watchlist', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('stocks_watchlist', 'current_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index('idx_stocks_watchlist_symbol', table_name='stocks_watchlist')
    op.create_index(op.f('ix_stocks_watchlist_is_active'), 'stocks_watchlist', ['is_active'], unique=False)
    op.create_index(op.f('ix_stocks_watchlist_symbol'), 'stocks_watchlist', ['symbol'], unique=True)
    op.alter_column('system_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('system_logs', 'logger',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text('("app")'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_logs', 'logger',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text('("app")'))
    op.alter_column('system_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stocks_watchlist_symbol'), table_name='stocks_watchlist')
    op.drop_index(op.f('ix_stocks_watchlist_is_active'), table_name='stocks_watchlist')
    op.create_index('idx_stocks_watchlist_symbol', 'stocks_watchlist', ['symbol'], unique=False)
    op.alter_column('stocks_watchlist', 'current_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('stocks_watchlist', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.alter_column('stock_prices', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stock_prices', 'symbol',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stock_prices', 'stock_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('stock_prices', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'sentiment_data', type_='foreignkey')
    op.drop_index(op.f('ix_sentiment_data_sentiment_label'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_content_hash'), table_name='sentiment_data')
    op.drop_index('idx_sentiment_duplicate_check', table_name='sentiment_data')
    op.create_index('idx_sentiment_duplicate_check', 'sentiment_data', ['content_hash', 'stock_id', 'source'], unique=False)
    op.alter_column('sentiment_data', 'content_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sentiment_data', 'model_used',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sentiment_data', 'sentiment_label',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Neutral'"))
    op.alter_column('sentiment_data', 'confidence',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('sentiment_data', 'sentiment_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'source',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sentiment_data', 'stock_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('sentiment_data', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('news_articles', 'author',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('news_articles', 'source',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('news_articles', 'url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('news_articles', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('news_articles', 'stock_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('news_articles', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('reddit_posts',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('stock_id', sa.TEXT(), nullable=True),
    sa.Column('reddit_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('subreddit', sa.TEXT(), nullable=False),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('score', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('num_comments', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('created_utc', sa.DATETIME(), nullable=False),
    sa.Column('sentiment_score', sa.NUMERIC(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), nullable=True),
    sa.Column('stock_mentions', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_watchlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id')
    )
    op.create_table('_alembic_tmp_sentiment_data',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('stock_id', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=False),
    sa.Column('sentiment_score', sa.REAL(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('sentiment_label', sa.TEXT(), server_default=sa.text("'Neutral'"), nullable=False),
    sa.Column('model_used', sa.TEXT(), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('additional_metadata', sqlite.JSON(), nullable=True),
    sa.Column('content_hash', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hackernews_posts')
    # ### end Alembic commands ###
